import { livePortfolioProjects } from "@/lib/live-portfolio-projects"

export type PortfolioCategory =
  | "ecommerce"
  | "publishing"
  | "healthcare"
  | "hospitality"
  | "trades"
  | "education"
  | "professional"
  | "food"
  | "software"
  | "websites"

export type PortfolioProject = {
  id: number
  slug: string
  name: string
  link: string
  category: PortfolioCategory
  categoryLabel: string
  categoryLabelAr: string
  description: string
  descriptionAr: string
  image: string
  featured?: boolean
  premium?: boolean
}

const archivePortfolioProjects: PortfolioProject[] = [
  {
    "id": 1,
    "slug": "clarivive-medinsight",
    "name": "Clarivive Medinsight",
    "link": "",
    "category": "healthcare",
    "categoryLabel": "Healthcare",
    "categoryLabelAr": "رعاية صحية",
    "description": "Patient-facing site with calm UX — services clarity, inquiry paths, and a premium clinical brand presence.",
    "descriptionAr": "موقع طبي هادئ وواضح — خدمات مفهومة ومسار تواصل ومظهر عيادي راقٍ.",
    "image": "/portfolio/portfolio_images/001_clarivive_medinsight.jpg"
  },
  {
    "id": 2,
    "slug": "quantum-code-solutions",
    "name": "Quantum Code Solutions",
    "link": "",
    "category": "software",
    "categoryLabel": "Software & tech",
    "categoryLabelAr": "برمجيات وتقنية",
    "description": "Product-grade digital presence — sharp messaging, modern UI, and a funnel that turns visitors into demos.",
    "descriptionAr": "حضور رقمي بمستوى المنتج — رسالة حادة وواجهة حديثة ومسار نحو العرض التجريبي.",
    "image": "/portfolio/portfolio_images/002_quantum_code_solutions.jpg"
  },
  {
    "id": 3,
    "slug": "techlab",
    "name": "TechLab",
    "link": "",
    "category": "software",
    "categoryLabel": "Software & tech",
    "categoryLabelAr": "برمجيات وتقنية",
    "description": "Product-grade digital presence — sharp messaging, modern UI, and a funnel that turns visitors into demos.",
    "descriptionAr": "حضور رقمي بمستوى المنتج — رسالة حادة وواجهة حديثة ومسار نحو العرض التجريبي.",
    "image": "/portfolio/portfolio_images/003_techlab.jpg"
  },
  {
    "id": 4,
    "slug": "am-visa-hub",
    "name": "AM Visa Hub",
    "link": "",
    "category": "professional",
    "categoryLabel": "Professional",
    "categoryLabelAr": "خدمات مهنية",
    "description": "Professional brand site — authority-first layout, clear services, and easy contact for high-intent leads.",
    "descriptionAr": "موقع احترافي يعكس السلطة — خدمات واضحة وتواصل سهل لعملاء جادين.",
    "image": "/portfolio/portfolio_images/004_am_visa_hub.jpg"
  },
  {
    "id": 5,
    "slug": "hafizabad-consultants",
    "name": "Hafizabad Consultants",
    "link": "",
    "category": "professional",
    "categoryLabel": "Professional",
    "categoryLabelAr": "خدمات مهنية",
    "description": "Professional brand site — authority-first layout, clear services, and easy contact for high-intent leads.",
    "descriptionAr": "موقع احترافي يعكس السلطة — خدمات واضحة وتواصل سهل لعملاء جادين.",
    "image": "/portfolio/portfolio_images/005_hafizabad_consultants.jpg"
  },
  {
    "id": 6,
    "slug": "ag1",
    "name": "AG1",
    "link": "",
    "category": "professional",
    "categoryLabel": "Professional",
    "categoryLabelAr": "خدمات مهنية",
    "description": "Professional brand site — authority-first layout, clear services, and easy contact for high-intent leads.",
    "descriptionAr": "موقع احترافي يعكس السلطة — خدمات واضحة وتواصل سهل لعملاء جادين.",
    "image": "/portfolio/portfolio_images/006_ag1.jpg"
  },
  {
    "id": 7,
    "slug": "scie-journal-publication",
    "name": "SCIE Journal Publication",
    "link": "",
    "category": "publishing",
    "categoryLabel": "Publishing",
    "categoryLabelAr": "نشر ومحتوى",
    "description": "Content platform designed for credibility — clear offers, author trust signals, and conversion-ready service pages.",
    "descriptionAr": "منصة محتوى تبني المصداقية — عروض واضحة وإشارات ثقة ومسارات تحويل للخدمات.",
    "image": "/portfolio/portfolio_images/007_scie_journal_publication.jpg"
  },
  {
    "id": 8,
    "slug": "page-one-insights",
    "name": "Page One Insights",
    "link": "",
    "category": "software",
    "categoryLabel": "Software & tech",
    "categoryLabelAr": "برمجيات وتقنية",
    "description": "Product-grade digital presence — sharp messaging, modern UI, and a funnel that turns visitors into demos.",
    "descriptionAr": "حضور رقمي بمستوى المنتج — رسالة حادة وواجهة حديثة ومسار نحو العرض التجريبي.",
    "image": "/portfolio/portfolio_images/008_page_one_insights.jpg"
  },
  {
    "id": 9,
    "slug": "fusion-box-vault",
    "name": "Fusion Box Vault",
    "link": "",
    "category": "software",
    "categoryLabel": "Software & tech",
    "categoryLabelAr": "برمجيات وتقنية",
    "description": "Product-grade digital presence — sharp messaging, modern UI, and a funnel that turns visitors into demos.",
    "descriptionAr": "حضور رقمي بمستوى المنتج — رسالة حادة وواجهة حديثة ومسار نحو العرض التجريبي.",
    "image": "/portfolio/portfolio_images/009_fusion_box_vault.jpg"
  },
  {
    "id": 10,
    "slug": "mczell-book-writings",
    "name": "McZell Book Writings",
    "link": "",
    "category": "publishing",
    "categoryLabel": "Publishing",
    "categoryLabelAr": "نشر ومحتوى",
    "description": "Content platform designed for credibility — clear offers, author trust signals, and conversion-ready service pages.",
    "descriptionAr": "منصة محتوى تبني المصداقية — عروض واضحة وإشارات ثقة ومسارات تحويل للخدمات.",
    "image": "/portfolio/portfolio_images/010_mczell_book_writings.jpg"
  },
  {
    "id": 11,
    "slug": "wreckreports-com",
    "name": "WreckReports.com",
    "link": "",
    "category": "software",
    "categoryLabel": "Software & tech",
    "categoryLabelAr": "برمجيات وتقنية",
    "description": "Product-grade digital presence — sharp messaging, modern UI, and a funnel that turns visitors into demos.",
    "descriptionAr": "حضور رقمي بمستوى المنتج — رسالة حادة وواجهة حديثة ومسار نحو العرض التجريبي.",
    "image": "/portfolio/portfolio_images/011_wreckreports_com.jpg"
  },
  {
    "id": 12,
    "slug": "skins-by-linds",
    "name": "Skins by Linds",
    "link": "",
    "category": "professional",
    "categoryLabel": "Professional",
    "categoryLabelAr": "خدمات مهنية",
    "description": "Professional brand site — authority-first layout, clear services, and easy contact for high-intent leads.",
    "descriptionAr": "موقع احترافي يعكس السلطة — خدمات واضحة وتواصل سهل لعملاء جادين.",
    "image": "/portfolio/portfolio_images/012_skins_by_linds.jpg"
  },
  {
    "id": 13,
    "slug": "consol-techs",
    "name": "Consol Techs",
    "link": "",
    "category": "software",
    "categoryLabel": "Software & tech",
    "categoryLabelAr": "برمجيات وتقنية",
    "description": "Product-grade digital presence — sharp messaging, modern UI, and a funnel that turns visitors into demos.",
    "descriptionAr": "حضور رقمي بمستوى المنتج — رسالة حادة وواجهة حديثة ومسار نحو العرض التجريبي.",
    "image": "/portfolio/portfolio_images/013_consol_techs.jpg"
  },
  {
    "id": 14,
    "slug": "hijab-e-haya",
    "name": "Hijab-e-Haya",
    "link": "",
    "category": "ecommerce",
    "categoryLabel": "E-commerce",
    "categoryLabelAr": "تجارة إلكترونية",
    "description": "Storefront built to sell — clean product pages, fast checkout paths, and a brand look that earns trust.",
    "descriptionAr": "متجر إلكتروني جاهز للبيع — صفحات منتجات واضحة ومسار شراء سريع وهوية تبني الثقة.",
    "image": "/portfolio/portfolio_images/014_hijab_e_haya.jpg"
  },
  {
    "id": 15,
    "slug": "amy-b",
    "name": "Amy B.",
    "link": "",
    "category": "professional",
    "categoryLabel": "Professional",
    "categoryLabelAr": "خدمات مهنية",
    "description": "Professional brand site — authority-first layout, clear services, and easy contact for high-intent leads.",
    "descriptionAr": "موقع احترافي يعكس السلطة — خدمات واضحة وتواصل سهل لعملاء جادين.",
    "image": "/portfolio/portfolio_images/015_amy_b.jpg"
  },
  {
    "id": 16,
    "slug": "research-publications-uk",
    "name": "Research Publications UK",
    "link": "",
    "category": "publishing",
    "categoryLabel": "Publishing",
    "categoryLabelAr": "نشر ومحتوى",
    "description": "Content platform designed for credibility — clear offers, author trust signals, and conversion-ready service pages.",
    "descriptionAr": "منصة محتوى تبني المصداقية — عروض واضحة وإشارات ثقة ومسارات تحويل للخدمات.",
    "image": "/portfolio/portfolio_images/016_research_publications_uk.jpg"
  },
  {
    "id": 17,
    "slug": "krnl",
    "name": "Krnl",
    "link": "",
    "category": "software",
    "categoryLabel": "Software & tech",
    "categoryLabelAr": "برمجيات وتقنية",
    "description": "Product-grade digital presence — sharp messaging, modern UI, and a funnel that turns visitors into demos.",
    "descriptionAr": "حضور رقمي بمستوى المنتج — رسالة حادة وواجهة حديثة ومسار نحو العرض التجريبي.",
    "image": "/portfolio/portfolio_images/017_krnl.jpg"
  },
  {
    "id": 18,
    "slug": "elevara-learning",
    "name": "Elevara Learning",
    "link": "",
    "category": "education",
    "categoryLabel": "Education",
    "categoryLabelAr": "تعليم",
    "description": "Learning brand online — course clarity, enrollment intent, and a modern academy presence.",
    "descriptionAr": "حضور أكاديمي حديث — وضوح الدورات ونية التسجيل وهوية تعليمية قوية.",
    "image": "/portfolio/portfolio_images/018_elevara_learning.jpg"
  },
  {
    "id": 19,
    "slug": "innovations-logistics",
    "name": "Innovations Logistics",
    "link": "",
    "category": "hospitality",
    "categoryLabel": "Hospitality",
    "categoryLabelAr": "ضيافة وسفر",
    "description": "Guest-ready web experience — booking intent, destination storytelling, and mobile-first conversion.",
    "descriptionAr": "تجربة ويب للضيوف — نية حجز وقصة وجهة وتصميم أولاً للجوال.",
    "image": "/portfolio/portfolio_images/019_innovations_logistics.jpg"
  },
  {
    "id": 20,
    "slug": "cleaning-scientists",
    "name": "Cleaning Scientists",
    "link": "",
    "category": "publishing",
    "categoryLabel": "Publishing",
    "categoryLabelAr": "نشر ومحتوى",
    "description": "Content platform designed for credibility — clear offers, author trust signals, and conversion-ready service pages.",
    "descriptionAr": "منصة محتوى تبني المصداقية — عروض واضحة وإشارات ثقة ومسارات تحويل للخدمات.",
    "image": "/portfolio/portfolio_images/020_cleaning_scientists.jpg"
  },
  {
    "id": 21,
    "slug": "alpha-digify",
    "name": "Alpha Digify",
    "link": "",
    "category": "software",
    "categoryLabel": "Software & tech",
    "categoryLabelAr": "برمجيات وتقنية",
    "description": "Product-grade digital presence — sharp messaging, modern UI, and a funnel that turns visitors into demos.",
    "descriptionAr": "حضور رقمي بمستوى المنتج — رسالة حادة وواجهة حديثة ومسار نحو العرض التجريبي.",
    "image": "/portfolio/portfolio_images/021_alpha_digify.jpg"
  },
  {
    "id": 22,
    "slug": "blackhawk-electric",
    "name": "Blackhawk Electric",
    "link": "",
    "category": "trades",
    "categoryLabel": "Local services",
    "categoryLabelAr": "خدمات محلية",
    "description": "Local-service website that wins calls — strong CTAs, service proof, and a look that feels established.",
    "descriptionAr": "موقع خدمات محلية يجلب المكالمات — دعوات واضحة وإثبات عمل ومظهر احترافي.",
    "image": "/portfolio/portfolio_images/022_blackhawk_electric.jpg"
  },
  {
    "id": 23,
    "slug": "floating-docks-florida",
    "name": "Floating Docks Florida",
    "link": "",
    "category": "hospitality",
    "categoryLabel": "Hospitality",
    "categoryLabelAr": "ضيافة وسفر",
    "description": "Guest-ready web experience — booking intent, destination storytelling, and mobile-first conversion.",
    "descriptionAr": "تجربة ويب للضيوف — نية حجز وقصة وجهة وتصميم أولاً للجوال.",
    "image": "/portfolio/portfolio_images/023_floating_docks_florida.jpg"
  },
  {
    "id": 24,
    "slug": "vantrex-digital",
    "name": "Vantrex Digital",
    "link": "",
    "category": "software",
    "categoryLabel": "Software & tech",
    "categoryLabelAr": "برمجيات وتقنية",
    "description": "Product-grade digital presence — sharp messaging, modern UI, and a funnel that turns visitors into demos.",
    "descriptionAr": "حضور رقمي بمستوى المنتج — رسالة حادة وواجهة حديثة ومسار نحو العرض التجريبي.",
    "image": "/portfolio/portfolio_images/024_vantrex_digital.jpg"
  },
  {
    "id": 25,
    "slug": "nexovia-solutions",
    "name": "Nexovia Solutions",
    "link": "",
    "category": "software",
    "categoryLabel": "Software & tech",
    "categoryLabelAr": "برمجيات وتقنية",
    "description": "Product-grade digital presence — sharp messaging, modern UI, and a funnel that turns visitors into demos.",
    "descriptionAr": "حضور رقمي بمستوى المنتج — رسالة حادة وواجهة حديثة ومسار نحو العرض التجريبي.",
    "image": "/portfolio/portfolio_images/025_nexovia_solutions.jpg"
  },
  {
    "id": 26,
    "slug": "time-to-pack-travel",
    "name": "Time to Pack Travel",
    "link": "",
    "category": "hospitality",
    "categoryLabel": "Hospitality",
    "categoryLabelAr": "ضيافة وسفر",
    "description": "Guest-ready web experience — booking intent, destination storytelling, and mobile-first conversion.",
    "descriptionAr": "تجربة ويب للضيوف — نية حجز وقصة وجهة وتصميم أولاً للجوال.",
    "image": "/portfolio/portfolio_images/026_time_to_pack_travel.jpg"
  },
  {
    "id": 27,
    "slug": "american-best-publishers",
    "name": "American Best Publishers",
    "link": "",
    "category": "publishing",
    "categoryLabel": "Publishing",
    "categoryLabelAr": "نشر ومحتوى",
    "description": "Content platform designed for credibility — clear offers, author trust signals, and conversion-ready service pages.",
    "descriptionAr": "منصة محتوى تبني المصداقية — عروض واضحة وإشارات ثقة ومسارات تحويل للخدمات.",
    "image": "/portfolio/portfolio_images/027_american_best_publishers.jpg"
  },
  {
    "id": 28,
    "slug": "islamic-qurbani",
    "name": "Islamic Qurbani",
    "link": "",
    "category": "websites",
    "categoryLabel": "Websites",
    "categoryLabelAr": "مواقع",
    "description": "Custom website crafted to convert — premium design, clear story, and performance that feels instant.",
    "descriptionAr": "موقع مخصص للتحويل — تصميم راقٍ وقصة واضحة وأداء سريع.",
    "image": "/portfolio/portfolio_images/028_islamic_qurbani.jpg"
  },
  {
    "id": 29,
    "slug": "less-than-1-thousand",
    "name": "Less Than 1 Thousand",
    "link": "",
    "category": "websites",
    "categoryLabel": "Websites",
    "categoryLabelAr": "مواقع",
    "description": "Custom website crafted to convert — premium design, clear story, and performance that feels instant.",
    "descriptionAr": "موقع مخصص للتحويل — تصميم راقٍ وقصة واضحة وأداء سريع.",
    "image": "/portfolio/portfolio_images/029_less_than_1_thousand.jpg"
  },
  {
    "id": 30,
    "slug": "fury-bags",
    "name": "Fury Bags",
    "link": "",
    "category": "ecommerce",
    "categoryLabel": "E-commerce",
    "categoryLabelAr": "تجارة إلكترونية",
    "description": "Storefront built to sell — clean product pages, fast checkout paths, and a brand look that earns trust.",
    "descriptionAr": "متجر إلكتروني جاهز للبيع — صفحات منتجات واضحة ومسار شراء سريع وهوية تبني الثقة.",
    "image": "/portfolio/portfolio_images/030_fury_bags.jpg"
  },
  {
    "id": 31,
    "slug": "quirky-bags",
    "name": "Quirky Bags",
    "link": "",
    "category": "ecommerce",
    "categoryLabel": "E-commerce",
    "categoryLabelAr": "تجارة إلكترونية",
    "description": "Storefront built to sell — clean product pages, fast checkout paths, and a brand look that earns trust.",
    "descriptionAr": "متجر إلكتروني جاهز للبيع — صفحات منتجات واضحة ومسار شراء سريع وهوية تبني الثقة.",
    "image": "/portfolio/portfolio_images/031_quirky_bags.jpg"
  },
  {
    "id": 32,
    "slug": "mad-extra-seo",
    "name": "Mad Extra SEO",
    "link": "",
    "category": "software",
    "categoryLabel": "Software & tech",
    "categoryLabelAr": "برمجيات وتقنية",
    "description": "Product-grade digital presence — sharp messaging, modern UI, and a funnel that turns visitors into demos.",
    "descriptionAr": "حضور رقمي بمستوى المنتج — رسالة حادة وواجهة حديثة ومسار نحو العرض التجريبي.",
    "image": "/portfolio/portfolio_images/032_mad_extra_seo.jpg"
  },
  {
    "id": 33,
    "slug": "izi-driving-academy",
    "name": "iZi Driving Academy",
    "link": "",
    "category": "education",
    "categoryLabel": "Education",
    "categoryLabelAr": "تعليم",
    "description": "Learning brand online — course clarity, enrollment intent, and a modern academy presence.",
    "descriptionAr": "حضور أكاديمي حديث — وضوح الدورات ونية التسجيل وهوية تعليمية قوية.",
    "image": "/portfolio/portfolio_images/033_izi_driving_academy.jpg"
  },
  {
    "id": 34,
    "slug": "homsstore",
    "name": "Homsstore",
    "link": "",
    "category": "ecommerce",
    "categoryLabel": "E-commerce",
    "categoryLabelAr": "تجارة إلكترونية",
    "description": "Storefront built to sell — clean product pages, fast checkout paths, and a brand look that earns trust.",
    "descriptionAr": "متجر إلكتروني جاهز للبيع — صفحات منتجات واضحة ومسار شراء سريع وهوية تبني الثقة.",
    "image": "/portfolio/portfolio_images/034_homsstore.jpg"
  },
  {
    "id": 35,
    "slug": "thoppia",
    "name": "Thoppia",
    "link": "",
    "category": "ecommerce",
    "categoryLabel": "E-commerce",
    "categoryLabelAr": "تجارة إلكترونية",
    "description": "Storefront built to sell — clean product pages, fast checkout paths, and a brand look that earns trust.",
    "descriptionAr": "متجر إلكتروني جاهز للبيع — صفحات منتجات واضحة ومسار شراء سريع وهوية تبني الثقة.",
    "image": "/portfolio/portfolio_images/035_thoppia.jpg"
  },
  {
    "id": 36,
    "slug": "zevitech",
    "name": "Zevitech",
    "link": "",
    "category": "software",
    "categoryLabel": "Software & tech",
    "categoryLabelAr": "برمجيات وتقنية",
    "description": "Product-grade digital presence — sharp messaging, modern UI, and a funnel that turns visitors into demos.",
    "descriptionAr": "حضور رقمي بمستوى المنتج — رسالة حادة وواجهة حديثة ومسار نحو العرض التجريبي.",
    "image": "/portfolio/portfolio_images/036_zevitech.jpg"
  },
  {
    "id": 37,
    "slug": "madiha-x-digital",
    "name": "Madiha X Digital",
    "link": "",
    "category": "software",
    "categoryLabel": "Software & tech",
    "categoryLabelAr": "برمجيات وتقنية",
    "description": "Product-grade digital presence — sharp messaging, modern UI, and a funnel that turns visitors into demos.",
    "descriptionAr": "حضور رقمي بمستوى المنتج — رسالة حادة وواجهة حديثة ومسار نحو العرض التجريبي.",
    "image": "/portfolio/portfolio_images/037_madiha_x_digital.jpg"
  },
  {
    "id": 38,
    "slug": "she-chef-n",
    "name": "She Chef'N",
    "link": "",
    "category": "food",
    "categoryLabel": "Food & dining",
    "categoryLabelAr": "أغذية ومطاعم",
    "description": "Food brand experience — appetite-led visuals, menu clarity, and reservation or order intent.",
    "descriptionAr": "تجربة علامة غذائية — صور جذابة ووضوح القائمة ونية طلب أو حجز.",
    "image": "/portfolio/portfolio_images/038_she_chef_n.jpg"
  },
  {
    "id": 39,
    "slug": "vseebox-online-shop",
    "name": "vSeeBox Online Shop",
    "link": "",
    "category": "ecommerce",
    "categoryLabel": "E-commerce",
    "categoryLabelAr": "تجارة إلكترونية",
    "description": "Storefront built to sell — clean product pages, fast checkout paths, and a brand look that earns trust.",
    "descriptionAr": "متجر إلكتروني جاهز للبيع — صفحات منتجات واضحة ومسار شراء سريع وهوية تبني الثقة.",
    "image": "/portfolio/portfolio_images/039_vseebox_online_shop.jpg"
  },
  {
    "id": 40,
    "slug": "superboxx-shop",
    "name": "SuperBoxx Shop",
    "link": "",
    "category": "ecommerce",
    "categoryLabel": "E-commerce",
    "categoryLabelAr": "تجارة إلكترونية",
    "description": "Storefront built to sell — clean product pages, fast checkout paths, and a brand look that earns trust.",
    "descriptionAr": "متجر إلكتروني جاهز للبيع — صفحات منتجات واضحة ومسار شراء سريع وهوية تبني الثقة.",
    "image": "/portfolio/portfolio_images/040_superboxx_shop.jpg"
  },
  {
    "id": 41,
    "slug": "headphone-by-budget",
    "name": "Headphone by Budget",
    "link": "",
    "category": "ecommerce",
    "categoryLabel": "E-commerce",
    "categoryLabelAr": "تجارة إلكترونية",
    "description": "Storefront built to sell — clean product pages, fast checkout paths, and a brand look that earns trust.",
    "descriptionAr": "متجر إلكتروني جاهز للبيع — صفحات منتجات واضحة ومسار شراء سريع وهوية تبني الثقة.",
    "image": "/portfolio/portfolio_images/041_headphone_by_budget.jpg"
  },
  {
    "id": 42,
    "slug": "kukon-store",
    "name": "Kukon Store",
    "link": "",
    "category": "ecommerce",
    "categoryLabel": "E-commerce",
    "categoryLabelAr": "تجارة إلكترونية",
    "description": "Storefront built to sell — clean product pages, fast checkout paths, and a brand look that earns trust.",
    "descriptionAr": "متجر إلكتروني جاهز للبيع — صفحات منتجات واضحة ومسار شراء سريع وهوية تبني الثقة.",
    "image": "/portfolio/portfolio_images/042_kukon_store.jpg"
  },
  {
    "id": 43,
    "slug": "arcticfit",
    "name": "ArcticFit",
    "link": "",
    "category": "ecommerce",
    "categoryLabel": "E-commerce",
    "categoryLabelAr": "تجارة إلكترونية",
    "description": "Storefront built to sell — clean product pages, fast checkout paths, and a brand look that earns trust.",
    "descriptionAr": "متجر إلكتروني جاهز للبيع — صفحات منتجات واضحة ومسار شراء سريع وهوية تبني الثقة.",
    "image": "/portfolio/portfolio_images/043_arcticfit.jpg"
  },
  {
    "id": 44,
    "slug": "rosh",
    "name": "Rosh",
    "link": "",
    "category": "ecommerce",
    "categoryLabel": "E-commerce",
    "categoryLabelAr": "تجارة إلكترونية",
    "description": "Storefront built to sell — clean product pages, fast checkout paths, and a brand look that earns trust.",
    "descriptionAr": "متجر إلكتروني جاهز للبيع — صفحات منتجات واضحة ومسار شراء سريع وهوية تبني الثقة.",
    "image": "/portfolio/portfolio_images/044_rosh.jpg"
  },
  {
    "id": 45,
    "slug": "techariba-enterprises",
    "name": "TechAriba Enterprises",
    "link": "",
    "category": "software",
    "categoryLabel": "Software & tech",
    "categoryLabelAr": "برمجيات وتقنية",
    "description": "Product-grade digital presence — sharp messaging, modern UI, and a funnel that turns visitors into demos.",
    "descriptionAr": "حضور رقمي بمستوى المنتج — رسالة حادة وواجهة حديثة ومسار نحو العرض التجريبي.",
    "image": "/portfolio/portfolio_images/045_techariba_enterprises.jpg"
  },
  {
    "id": 46,
    "slug": "ebone-network",
    "name": "Ebone Network",
    "link": "",
    "category": "software",
    "categoryLabel": "Software & tech",
    "categoryLabelAr": "برمجيات وتقنية",
    "description": "Product-grade digital presence — sharp messaging, modern UI, and a funnel that turns visitors into demos.",
    "descriptionAr": "حضور رقمي بمستوى المنتج — رسالة حادة وواجهة حديثة ومسار نحو العرض التجريبي.",
    "image": "/portfolio/portfolio_images/046_ebone_network.jpg"
  },
  {
    "id": 47,
    "slug": "transworld-home",
    "name": "Transworld Home",
    "link": "",
    "category": "websites",
    "categoryLabel": "Websites",
    "categoryLabelAr": "مواقع",
    "description": "Custom website crafted to convert — premium design, clear story, and performance that feels instant.",
    "descriptionAr": "موقع مخصص للتحويل — تصميم راقٍ وقصة واضحة وأداء سريع.",
    "image": "/portfolio/portfolio_images/047_transworld_home.jpg"
  },
  {
    "id": 48,
    "slug": "revon-gliders",
    "name": "Revon Gliders",
    "link": "",
    "category": "ecommerce",
    "categoryLabel": "E-commerce",
    "categoryLabelAr": "تجارة إلكترونية",
    "description": "Storefront built to sell — clean product pages, fast checkout paths, and a brand look that earns trust.",
    "descriptionAr": "متجر إلكتروني جاهز للبيع — صفحات منتجات واضحة ومسار شراء سريع وهوية تبني الثقة.",
    "image": "/portfolio/portfolio_images/048_revon_gliders.jpg"
  },
  {
    "id": 49,
    "slug": "the-partners-work",
    "name": "The Partners Work",
    "link": "",
    "category": "professional",
    "categoryLabel": "Professional",
    "categoryLabelAr": "خدمات مهنية",
    "description": "Professional brand site — authority-first layout, clear services, and easy contact for high-intent leads.",
    "descriptionAr": "موقع احترافي يعكس السلطة — خدمات واضحة وتواصل سهل لعملاء جادين.",
    "image": "/portfolio/portfolio_images/049_the_partners_work.jpg"
  },
  {
    "id": 50,
    "slug": "yamm-buffet",
    "name": "Yamm Buffet",
    "link": "",
    "category": "hospitality",
    "categoryLabel": "Hospitality",
    "categoryLabelAr": "ضيافة وسفر",
    "description": "Guest-ready web experience — booking intent, destination storytelling, and mobile-first conversion.",
    "descriptionAr": "تجربة ويب للضيوف — نية حجز وقصة وجهة وتصميم أولاً للجوال.",
    "image": "/portfolio/portfolio_images/050_yamm_buffet.jpg"
  },
  {
    "id": 51,
    "slug": "novelle-ghostwriting",
    "name": "Novelle Ghostwriting",
    "link": "",
    "category": "publishing",
    "categoryLabel": "Publishing",
    "categoryLabelAr": "نشر ومحتوى",
    "description": "Content platform designed for credibility — clear offers, author trust signals, and conversion-ready service pages.",
    "descriptionAr": "منصة محتوى تبني المصداقية — عروض واضحة وإشارات ثقة ومسارات تحويل للخدمات.",
    "image": "/portfolio/portfolio_images/051_novelle_ghostwriting.jpg"
  },
  {
    "id": 52,
    "slug": "scopus-article-publication",
    "name": "Scopus Article Publication",
    "link": "",
    "category": "publishing",
    "categoryLabel": "Publishing",
    "categoryLabelAr": "نشر ومحتوى",
    "description": "Content platform designed for credibility — clear offers, author trust signals, and conversion-ready service pages.",
    "descriptionAr": "منصة محتوى تبني المصداقية — عروض واضحة وإشارات ثقة ومسارات تحويل للخدمات.",
    "image": "/portfolio/portfolio_images/052_scopus_article_publication.jpg"
  },
  {
    "id": 53,
    "slug": "bishop-prof-daniel-a-m-ghansah",
    "name": "Bishop Prof. Daniel A. M. Ghansah",
    "link": "",
    "category": "ecommerce",
    "categoryLabel": "E-commerce",
    "categoryLabelAr": "تجارة إلكترونية",
    "description": "Storefront built to sell — clean product pages, fast checkout paths, and a brand look that earns trust.",
    "descriptionAr": "متجر إلكتروني جاهز للبيع — صفحات منتجات واضحة ومسار شراء سريع وهوية تبني الثقة.",
    "image": "/portfolio/portfolio_images/053_bishop_prof_daniel_a_m_ghansah.jpg"
  },
  {
    "id": 54,
    "slug": "scopus-journal-services",
    "name": "Scopus Journal Services",
    "link": "",
    "category": "publishing",
    "categoryLabel": "Publishing",
    "categoryLabelAr": "نشر ومحتوى",
    "description": "Content platform designed for credibility — clear offers, author trust signals, and conversion-ready service pages.",
    "descriptionAr": "منصة محتوى تبني المصداقية — عروض واضحة وإشارات ثقة ومسارات تحويل للخدمات.",
    "image": "/portfolio/portfolio_images/054_scopus_journal_services.jpg"
  },
  {
    "id": 55,
    "slug": "journal-publication-house",
    "name": "Journal Publication House",
    "link": "",
    "category": "publishing",
    "categoryLabel": "Publishing",
    "categoryLabelAr": "نشر ومحتوى",
    "description": "Content platform designed for credibility — clear offers, author trust signals, and conversion-ready service pages.",
    "descriptionAr": "منصة محتوى تبني المصداقية — عروض واضحة وإشارات ثقة ومسارات تحويل للخدمات.",
    "image": "/portfolio/portfolio_images/055_journal_publication_house.jpg"
  },
  {
    "id": 56,
    "slug": "sci-journal-publications",
    "name": "SCI Journal Publications",
    "link": "",
    "category": "publishing",
    "categoryLabel": "Publishing",
    "categoryLabelAr": "نشر ومحتوى",
    "description": "Content platform designed for credibility — clear offers, author trust signals, and conversion-ready service pages.",
    "descriptionAr": "منصة محتوى تبني المصداقية — عروض واضحة وإشارات ثقة ومسارات تحويل للخدمات.",
    "image": "/portfolio/portfolio_images/056_sci_journal_publications.jpg"
  },
  {
    "id": 57,
    "slug": "esci-journal-publication",
    "name": "ESCI Journal Publication",
    "link": "",
    "category": "publishing",
    "categoryLabel": "Publishing",
    "categoryLabelAr": "نشر ومحتوى",
    "description": "Content platform designed for credibility — clear offers, author trust signals, and conversion-ready service pages.",
    "descriptionAr": "منصة محتوى تبني المصداقية — عروض واضحة وإشارات ثقة ومسارات تحويل للخدمات.",
    "image": "/portfolio/portfolio_images/057_esci_journal_publication.jpg"
  },
  {
    "id": 58,
    "slug": "buzzline-digital",
    "name": "Buzzline Digital",
    "link": "",
    "category": "software",
    "categoryLabel": "Software & tech",
    "categoryLabelAr": "برمجيات وتقنية",
    "description": "Product-grade digital presence — sharp messaging, modern UI, and a funnel that turns visitors into demos.",
    "descriptionAr": "حضور رقمي بمستوى المنتج — رسالة حادة وواجهة حديثة ومسار نحو العرض التجريبي.",
    "image": "/portfolio/portfolio_images/058_buzzline_digital.jpg"
  },
  {
    "id": 59,
    "slug": "ssci-journal-publication",
    "name": "SSCI Journal Publication",
    "link": "",
    "category": "publishing",
    "categoryLabel": "Publishing",
    "categoryLabelAr": "نشر ومحتوى",
    "description": "Content platform designed for credibility — clear offers, author trust signals, and conversion-ready service pages.",
    "descriptionAr": "منصة محتوى تبني المصداقية — عروض واضحة وإشارات ثقة ومسارات تحويل للخدمات.",
    "image": "/portfolio/portfolio_images/059_ssci_journal_publication.jpg"
  },
  {
    "id": 60,
    "slug": "emerald-publication-uk",
    "name": "Emerald Publication UK",
    "link": "",
    "category": "publishing",
    "categoryLabel": "Publishing",
    "categoryLabelAr": "نشر ومحتوى",
    "description": "Content platform designed for credibility — clear offers, author trust signals, and conversion-ready service pages.",
    "descriptionAr": "منصة محتوى تبني المصداقية — عروض واضحة وإشارات ثقة ومسارات تحويل للخدمات.",
    "image": "/portfolio/portfolio_images/060_emerald_publication_uk.jpg"
  },
  {
    "id": 61,
    "slug": "kef",
    "name": "KEF",
    "link": "",
    "category": "websites",
    "categoryLabel": "Websites",
    "categoryLabelAr": "مواقع",
    "description": "Custom website crafted to convert — premium design, clear story, and performance that feels instant.",
    "descriptionAr": "موقع مخصص للتحويل — تصميم راقٍ وقصة واضحة وأداء سريع.",
    "image": "/portfolio/portfolio_images/061_kef.jpg"
  },
  {
    "id": 62,
    "slug": "khaleej-news-pakistan",
    "name": "Khaleej News Pakistan",
    "link": "",
    "category": "professional",
    "categoryLabel": "Professional",
    "categoryLabelAr": "خدمات مهنية",
    "description": "Professional brand site — authority-first layout, clear services, and easy contact for high-intent leads.",
    "descriptionAr": "موقع احترافي يعكس السلطة — خدمات واضحة وتواصل سهل لعملاء جادين.",
    "image": "/portfolio/portfolio_images/062_khaleej_news_pakistan.jpg"
  },
  {
    "id": 63,
    "slug": "consumer-help-group",
    "name": "Consumer Help Group",
    "link": "",
    "category": "professional",
    "categoryLabel": "Professional",
    "categoryLabelAr": "خدمات مهنية",
    "description": "Professional brand site — authority-first layout, clear services, and easy contact for high-intent leads.",
    "descriptionAr": "موقع احترافي يعكس السلطة — خدمات واضحة وتواصل سهل لعملاء جادين.",
    "image": "/portfolio/portfolio_images/063_consumer_help_group.jpg"
  },
  {
    "id": 64,
    "slug": "barblu-pompano",
    "name": "BarBlu Pompano",
    "link": "",
    "category": "hospitality",
    "categoryLabel": "Hospitality",
    "categoryLabelAr": "ضيافة وسفر",
    "description": "Guest-ready web experience — booking intent, destination storytelling, and mobile-first conversion.",
    "descriptionAr": "تجربة ويب للضيوف — نية حجز وقصة وجهة وتصميم أولاً للجوال.",
    "image": "/portfolio/portfolio_images/064_barblu_pompano.jpg"
  },
  {
    "id": 65,
    "slug": "results-medical-aesthetics",
    "name": "Results Medical Aesthetics",
    "link": "",
    "category": "healthcare",
    "categoryLabel": "Healthcare",
    "categoryLabelAr": "رعاية صحية",
    "description": "Patient-facing site with calm UX — services clarity, inquiry paths, and a premium clinical brand presence.",
    "descriptionAr": "موقع طبي هادئ وواضح — خدمات مفهومة ومسار تواصل ومظهر عيادي راقٍ.",
    "image": "/portfolio/portfolio_images/065_results_medical_aesthetics.jpg"
  },
  {
    "id": 66,
    "slug": "jd-handy-pro",
    "name": "JD Handy Pro",
    "link": "",
    "category": "trades",
    "categoryLabel": "Local services",
    "categoryLabelAr": "خدمات محلية",
    "description": "Local-service website that wins calls — strong CTAs, service proof, and a look that feels established.",
    "descriptionAr": "موقع خدمات محلية يجلب المكالمات — دعوات واضحة وإثبات عمل ومظهر احترافي.",
    "image": "/portfolio/portfolio_images/066_jd_handy_pro.jpg"
  },
  {
    "id": 67,
    "slug": "city-painting-construction",
    "name": "City Painting & Construction",
    "link": "",
    "category": "trades",
    "categoryLabel": "Local services",
    "categoryLabelAr": "خدمات محلية",
    "description": "Local-service website that wins calls — strong CTAs, service proof, and a look that feels established.",
    "descriptionAr": "موقع خدمات محلية يجلب المكالمات — دعوات واضحة وإثبات عمل ومظهر احترافي.",
    "image": "/portfolio/portfolio_images/067_city_painting_construction.jpg"
  },
  {
    "id": 68,
    "slug": "nulife-essentials",
    "name": "NuLife Essentials",
    "link": "",
    "category": "ecommerce",
    "categoryLabel": "E-commerce",
    "categoryLabelAr": "تجارة إلكترونية",
    "description": "Storefront built to sell — clean product pages, fast checkout paths, and a brand look that earns trust.",
    "descriptionAr": "متجر إلكتروني جاهز للبيع — صفحات منتجات واضحة ومسار شراء سريع وهوية تبني الثقة.",
    "image": "/portfolio/portfolio_images/068_nulife_essentials.jpg"
  },
  {
    "id": 69,
    "slug": "ninja-transfers",
    "name": "Ninja Transfers",
    "link": "",
    "category": "ecommerce",
    "categoryLabel": "E-commerce",
    "categoryLabelAr": "تجارة إلكترونية",
    "description": "Storefront built to sell — clean product pages, fast checkout paths, and a brand look that earns trust.",
    "descriptionAr": "متجر إلكتروني جاهز للبيع — صفحات منتجات واضحة ومسار شراء سريع وهوية تبني الثقة.",
    "image": "/portfolio/portfolio_images/069_ninja_transfers.jpg"
  },
  {
    "id": 70,
    "slug": "muhammad-hasan-masrur",
    "name": "Muhammad Hasan Masrur",
    "link": "",
    "category": "professional",
    "categoryLabel": "Professional",
    "categoryLabelAr": "خدمات مهنية",
    "description": "Professional brand site — authority-first layout, clear services, and easy contact for high-intent leads.",
    "descriptionAr": "موقع احترافي يعكس السلطة — خدمات واضحة وتواصل سهل لعملاء جادين.",
    "image": "/portfolio/portfolio_images/070_muhammad_hasan_masrur.jpg"
  },
  {
    "id": 71,
    "slug": "city-inn-express",
    "name": "City Inn Express",
    "link": "",
    "category": "hospitality",
    "categoryLabel": "Hospitality",
    "categoryLabelAr": "ضيافة وسفر",
    "description": "Guest-ready web experience — booking intent, destination storytelling, and mobile-first conversion.",
    "descriptionAr": "تجربة ويب للضيوف — نية حجز وقصة وجهة وتصميم أولاً للجوال.",
    "image": "/portfolio/portfolio_images/071_city_inn_express.jpg"
  },
  {
    "id": 72,
    "slug": "kindle-ghostwriting",
    "name": "Kindle Ghostwriting",
    "link": "",
    "category": "publishing",
    "categoryLabel": "Publishing",
    "categoryLabelAr": "نشر ومحتوى",
    "description": "Content platform designed for credibility — clear offers, author trust signals, and conversion-ready service pages.",
    "descriptionAr": "منصة محتوى تبني المصداقية — عروض واضحة وإشارات ثقة ومسارات تحويل للخدمات.",
    "image": "/portfolio/portfolio_images/072_kindle_ghostwriting.jpg"
  },
  {
    "id": 73,
    "slug": "eme-elevators",
    "name": "EME Elevators",
    "link": "",
    "category": "trades",
    "categoryLabel": "Local services",
    "categoryLabelAr": "خدمات محلية",
    "description": "Local-service website that wins calls — strong CTAs, service proof, and a look that feels established.",
    "descriptionAr": "موقع خدمات محلية يجلب المكالمات — دعوات واضحة وإثبات عمل ومظهر احترافي.",
    "image": "/portfolio/portfolio_images/073_eme_elevators.jpg"
  },
  {
    "id": 74,
    "slug": "evengreener",
    "name": "EvenGreener",
    "link": "",
    "category": "trades",
    "categoryLabel": "Local services",
    "categoryLabelAr": "خدمات محلية",
    "description": "Local-service website that wins calls — strong CTAs, service proof, and a look that feels established.",
    "descriptionAr": "موقع خدمات محلية يجلب المكالمات — دعوات واضحة وإثبات عمل ومظهر احترافي.",
    "image": "/portfolio/portfolio_images/074_evengreener.jpg"
  },
  {
    "id": 75,
    "slug": "land-stone-engineering",
    "name": "Land Stone Engineering",
    "link": "",
    "category": "trades",
    "categoryLabel": "Local services",
    "categoryLabelAr": "خدمات محلية",
    "description": "Local-service website that wins calls — strong CTAs, service proof, and a look that feels established.",
    "descriptionAr": "موقع خدمات محلية يجلب المكالمات — دعوات واضحة وإثبات عمل ومظهر احترافي.",
    "image": "/portfolio/portfolio_images/075_land_stone_engineering.jpg"
  },
  {
    "id": 76,
    "slug": "elite-outfits",
    "name": "Elite Outfits",
    "link": "",
    "category": "ecommerce",
    "categoryLabel": "E-commerce",
    "categoryLabelAr": "تجارة إلكترونية",
    "description": "Storefront built to sell — clean product pages, fast checkout paths, and a brand look that earns trust.",
    "descriptionAr": "متجر إلكتروني جاهز للبيع — صفحات منتجات واضحة ومسار شراء سريع وهوية تبني الثقة.",
    "image": "/portfolio/portfolio_images/076_elite_outfits.jpg"
  },
  {
    "id": 77,
    "slug": "mountain-cove-luxury-senior-care",
    "name": "Mountain Cove Luxury Senior Care",
    "link": "",
    "category": "healthcare",
    "categoryLabel": "Healthcare",
    "categoryLabelAr": "رعاية صحية",
    "description": "Patient-facing site with calm UX — services clarity, inquiry paths, and a premium clinical brand presence.",
    "descriptionAr": "موقع طبي هادئ وواضح — خدمات مفهومة ومسار تواصل ومظهر عيادي راقٍ.",
    "image": "/portfolio/portfolio_images/077_mountain_cove_luxury_senior_care.jpg"
  },
  {
    "id": 78,
    "slug": "the-dressing-room-2",
    "name": "The Dressing Room 2",
    "link": "",
    "category": "ecommerce",
    "categoryLabel": "E-commerce",
    "categoryLabelAr": "تجارة إلكترونية",
    "description": "Storefront built to sell — clean product pages, fast checkout paths, and a brand look that earns trust.",
    "descriptionAr": "متجر إلكتروني جاهز للبيع — صفحات منتجات واضحة ومسار شراء سريع وهوية تبني الثقة.",
    "image": "/portfolio/portfolio_images/078_the_dressing_room_2.jpg"
  },
  {
    "id": 79,
    "slug": "precision-plumbing-solutions",
    "name": "Precision Plumbing Solutions",
    "link": "",
    "category": "trades",
    "categoryLabel": "Local services",
    "categoryLabelAr": "خدمات محلية",
    "description": "Local-service website that wins calls — strong CTAs, service proof, and a look that feels established.",
    "descriptionAr": "موقع خدمات محلية يجلب المكالمات — دعوات واضحة وإثبات عمل ومظهر احترافي.",
    "image": "/portfolio/portfolio_images/079_precision_plumbing_solutions.jpg"
  },
  {
    "id": 80,
    "slug": "l-h-fence-construction",
    "name": "L & H Fence & Construction",
    "link": "",
    "category": "trades",
    "categoryLabel": "Local services",
    "categoryLabelAr": "خدمات محلية",
    "description": "Local-service website that wins calls — strong CTAs, service proof, and a look that feels established.",
    "descriptionAr": "موقع خدمات محلية يجلب المكالمات — دعوات واضحة وإثبات عمل ومظهر احترافي.",
    "image": "/portfolio/portfolio_images/080_l_h_fence_construction.jpg"
  },
  {
    "id": 81,
    "slug": "sloan-underground-construction",
    "name": "Sloan Underground Construction",
    "link": "",
    "category": "trades",
    "categoryLabel": "Local services",
    "categoryLabelAr": "خدمات محلية",
    "description": "Local-service website that wins calls — strong CTAs, service proof, and a look that feels established.",
    "descriptionAr": "موقع خدمات محلية يجلب المكالمات — دعوات واضحة وإثبات عمل ومظهر احترافي.",
    "image": "/portfolio/portfolio_images/081_sloan_underground_construction.jpg"
  },
  {
    "id": 82,
    "slug": "rmb-fence-deck",
    "name": "RMB Fence & Deck",
    "link": "",
    "category": "trades",
    "categoryLabel": "Local services",
    "categoryLabelAr": "خدمات محلية",
    "description": "Local-service website that wins calls — strong CTAs, service proof, and a look that feels established.",
    "descriptionAr": "موقع خدمات محلية يجلب المكالمات — دعوات واضحة وإثبات عمل ومظهر احترافي.",
    "image": "/portfolio/portfolio_images/082_rmb_fence_deck.jpg"
  },
  {
    "id": 83,
    "slug": "cr-construction-remodeling",
    "name": "CR Construction & Remodeling",
    "link": "",
    "category": "trades",
    "categoryLabel": "Local services",
    "categoryLabelAr": "خدمات محلية",
    "description": "Local-service website that wins calls — strong CTAs, service proof, and a look that feels established.",
    "descriptionAr": "موقع خدمات محلية يجلب المكالمات — دعوات واضحة وإثبات عمل ومظهر احترافي.",
    "image": "/portfolio/portfolio_images/083_cr_construction_remodeling.jpg"
  },
  {
    "id": 84,
    "slug": "three-amigos-lawn-landscape",
    "name": "Three Amigos Lawn & Landscape",
    "link": "",
    "category": "trades",
    "categoryLabel": "Local services",
    "categoryLabelAr": "خدمات محلية",
    "description": "Local-service website that wins calls — strong CTAs, service proof, and a look that feels established.",
    "descriptionAr": "موقع خدمات محلية يجلب المكالمات — دعوات واضحة وإثبات عمل ومظهر احترافي.",
    "image": "/portfolio/portfolio_images/084_three_amigos_lawn_landscape.jpg"
  },
  {
    "id": 85,
    "slug": "legacy-towing-transport",
    "name": "Legacy Towing & Transport",
    "link": "",
    "category": "trades",
    "categoryLabel": "Local services",
    "categoryLabelAr": "خدمات محلية",
    "description": "Local-service website that wins calls — strong CTAs, service proof, and a look that feels established.",
    "descriptionAr": "موقع خدمات محلية يجلب المكالمات — دعوات واضحة وإثبات عمل ومظهر احترافي.",
    "image": "/portfolio/portfolio_images/085_legacy_towing_transport.jpg"
  },
  {
    "id": 86,
    "slug": "rlb-electric",
    "name": "RLB Electric",
    "link": "",
    "category": "trades",
    "categoryLabel": "Local services",
    "categoryLabelAr": "خدمات محلية",
    "description": "Local-service website that wins calls — strong CTAs, service proof, and a look that feels established.",
    "descriptionAr": "موقع خدمات محلية يجلب المكالمات — دعوات واضحة وإثبات عمل ومظهر احترافي.",
    "image": "/portfolio/portfolio_images/086_rlb_electric.jpg"
  },
  {
    "id": 87,
    "slug": "sd-assembly-pros",
    "name": "SD Assembly Pros",
    "link": "",
    "category": "trades",
    "categoryLabel": "Local services",
    "categoryLabelAr": "خدمات محلية",
    "description": "Local-service website that wins calls — strong CTAs, service proof, and a look that feels established.",
    "descriptionAr": "موقع خدمات محلية يجلب المكالمات — دعوات واضحة وإثبات عمل ومظهر احترافي.",
    "image": "/portfolio/portfolio_images/087_sd_assembly_pros.jpg"
  },
  {
    "id": 88,
    "slug": "bluecat-carpet-cleaning",
    "name": "Bluecat Carpet Cleaning",
    "link": "",
    "category": "trades",
    "categoryLabel": "Local services",
    "categoryLabelAr": "خدمات محلية",
    "description": "Local-service website that wins calls — strong CTAs, service proof, and a look that feels established.",
    "descriptionAr": "موقع خدمات محلية يجلب المكالمات — دعوات واضحة وإثبات عمل ومظهر احترافي.",
    "image": "/portfolio/portfolio_images/088_bluecat_carpet_cleaning.jpg"
  },
  {
    "id": 89,
    "slug": "the-tree-man",
    "name": "The Tree Man",
    "link": "",
    "category": "trades",
    "categoryLabel": "Local services",
    "categoryLabelAr": "خدمات محلية",
    "description": "Local-service website that wins calls — strong CTAs, service proof, and a look that feels established.",
    "descriptionAr": "موقع خدمات محلية يجلب المكالمات — دعوات واضحة وإثبات عمل ومظهر احترافي.",
    "image": "/portfolio/portfolio_images/089_the_tree_man.jpg"
  },
  {
    "id": 90,
    "slug": "dunn-irrigation-landscapes",
    "name": "Dunn Irrigation & Landscapes",
    "link": "",
    "category": "trades",
    "categoryLabel": "Local services",
    "categoryLabelAr": "خدمات محلية",
    "description": "Local-service website that wins calls — strong CTAs, service proof, and a look that feels established.",
    "descriptionAr": "موقع خدمات محلية يجلب المكالمات — دعوات واضحة وإثبات عمل ومظهر احترافي.",
    "image": "/portfolio/portfolio_images/090_dunn_irrigation_landscapes.jpg"
  },
  {
    "id": 91,
    "slug": "complete-landscape-management",
    "name": "Complete Landscape Management",
    "link": "",
    "category": "trades",
    "categoryLabel": "Local services",
    "categoryLabelAr": "خدمات محلية",
    "description": "Local-service website that wins calls — strong CTAs, service proof, and a look that feels established.",
    "descriptionAr": "موقع خدمات محلية يجلب المكالمات — دعوات واضحة وإثبات عمل ومظهر احترافي.",
    "image": "/portfolio/portfolio_images/091_complete_landscape_management.jpg"
  },
  {
    "id": 92,
    "slug": "drywall-more-services",
    "name": "Drywall & More Services",
    "link": "",
    "category": "trades",
    "categoryLabel": "Local services",
    "categoryLabelAr": "خدمات محلية",
    "description": "Local-service website that wins calls — strong CTAs, service proof, and a look that feels established.",
    "descriptionAr": "موقع خدمات محلية يجلب المكالمات — دعوات واضحة وإثبات عمل ومظهر احترافي.",
    "image": "/portfolio/portfolio_images/092_drywall_more_services.jpg"
  },
  {
    "id": 93,
    "slug": "blair-s-tree-service",
    "name": "Blair's Tree Service",
    "link": "",
    "category": "trades",
    "categoryLabel": "Local services",
    "categoryLabelAr": "خدمات محلية",
    "description": "Local-service website that wins calls — strong CTAs, service proof, and a look that feels established.",
    "descriptionAr": "موقع خدمات محلية يجلب المكالمات — دعوات واضحة وإثبات عمل ومظهر احترافي.",
    "image": "/portfolio/portfolio_images/093_blair_s_tree_service.jpg"
  },
  {
    "id": 94,
    "slug": "handy-s-construction",
    "name": "Handy's Construction",
    "link": "",
    "category": "trades",
    "categoryLabel": "Local services",
    "categoryLabelAr": "خدمات محلية",
    "description": "Local-service website that wins calls — strong CTAs, service proof, and a look that feels established.",
    "descriptionAr": "موقع خدمات محلية يجلب المكالمات — دعوات واضحة وإثبات عمل ومظهر احترافي.",
    "image": "/portfolio/portfolio_images/094_handy_s_construction.jpg"
  },
  {
    "id": 95,
    "slug": "miracle-tree-services",
    "name": "Miracle Tree Services",
    "link": "",
    "category": "trades",
    "categoryLabel": "Local services",
    "categoryLabelAr": "خدمات محلية",
    "description": "Local-service website that wins calls — strong CTAs, service proof, and a look that feels established.",
    "descriptionAr": "موقع خدمات محلية يجلب المكالمات — دعوات واضحة وإثبات عمل ومظهر احترافي.",
    "image": "/portfolio/portfolio_images/095_miracle_tree_services.jpg"
  },
  {
    "id": 96,
    "slug": "tim-s-tree-service",
    "name": "Tim's Tree Service",
    "link": "",
    "category": "trades",
    "categoryLabel": "Local services",
    "categoryLabelAr": "خدمات محلية",
    "description": "Local-service website that wins calls — strong CTAs, service proof, and a look that feels established.",
    "descriptionAr": "موقع خدمات محلية يجلب المكالمات — دعوات واضحة وإثبات عمل ومظهر احترافي.",
    "image": "/portfolio/portfolio_images/096_tim_s_tree_service.jpg"
  },
  {
    "id": 97,
    "slug": "in-motion-getaways",
    "name": "In Motion Getaways",
    "link": "",
    "category": "hospitality",
    "categoryLabel": "Hospitality",
    "categoryLabelAr": "ضيافة وسفر",
    "description": "Guest-ready web experience — booking intent, destination storytelling, and mobile-first conversion.",
    "descriptionAr": "تجربة ويب للضيوف — نية حجز وقصة وجهة وتصميم أولاً للجوال.",
    "image": "/portfolio/portfolio_images/097_in_motion_getaways.jpg"
  },
  {
    "id": 98,
    "slug": "the-link-solutions",
    "name": "The Link Solutions",
    "link": "",
    "category": "software",
    "categoryLabel": "Software & tech",
    "categoryLabelAr": "برمجيات وتقنية",
    "description": "Product-grade digital presence — sharp messaging, modern UI, and a funnel that turns visitors into demos.",
    "descriptionAr": "حضور رقمي بمستوى المنتج — رسالة حادة وواجهة حديثة ومسار نحو العرض التجريبي.",
    "image": "/portfolio/portfolio_images/098_the_link_solutions.jpg"
  },
  {
    "id": 99,
    "slug": "quantum-technologies",
    "name": "Quantum Technologies",
    "link": "",
    "category": "software",
    "categoryLabel": "Software & tech",
    "categoryLabelAr": "برمجيات وتقنية",
    "description": "Product-grade digital presence — sharp messaging, modern UI, and a funnel that turns visitors into demos.",
    "descriptionAr": "حضور رقمي بمستوى المنتج — رسالة حادة وواجهة حديثة ومسار نحو العرض التجريبي.",
    "image": "/portfolio/portfolio_images/099_quantum_technologies.jpg"
  },
  {
    "id": 100,
    "slug": "krista-tancredo",
    "name": "Krista Tancredo",
    "link": "",
    "category": "professional",
    "categoryLabel": "Professional",
    "categoryLabelAr": "خدمات مهنية",
    "description": "Professional brand site — authority-first layout, clear services, and easy contact for high-intent leads.",
    "descriptionAr": "موقع احترافي يعكس السلطة — خدمات واضحة وتواصل سهل لعملاء جادين.",
    "image": "/portfolio/portfolio_images/100_krista_tancredo.jpg"
  }
]

export const portfolioProjects: PortfolioProject[] = [
  ...livePortfolioProjects,
  ...archivePortfolioProjects,
]

export const portfolioCategories = [
  { id: "all" as const, label: "All projects", labelAr: "كل المشاريع" },
  { id: "software" as const, label: "Software & tech", labelAr: "برمجيات وتقنية" },
  { id: "ecommerce" as const, label: "E-commerce", labelAr: "تجارة إلكترونية" },
  { id: "trades" as const, label: "Local services", labelAr: "خدمات محلية" },
  { id: "publishing" as const, label: "Publishing", labelAr: "نشر ومحتوى" },
  { id: "hospitality" as const, label: "Hospitality", labelAr: "ضيافة وسفر" },
  { id: "healthcare" as const, label: "Healthcare", labelAr: "رعاية صحية" },
  { id: "professional" as const, label: "Professional", labelAr: "خدمات مهنية" },
  { id: "education" as const, label: "Education", labelAr: "تعليم" },
  { id: "food" as const, label: "Food & dining", labelAr: "أغذية ومطاعم" },
  { id: "websites" as const, label: "Websites", labelAr: "مواقع" },
] as const

export function getPortfolioProject(slug: string) {
  return portfolioProjects.find((p) => p.slug === slug)
}
